# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Install pre-commit itself:
#   $ pip install pre-commit
#     OR
#   $ brew install pre-commit
#
# Update all pre-commit hooks to latest version:
#   $ pre-commit autoupdate
#
# Install all pre-commit hooks locally:
#   $ pre-commit install
#
# Apply a given pre-commit hook to all files:
#   $ pre-commit run --all-files <id>
#
# Apply all pre-commit hooks to all files:
#   $ pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
  - repo: https://github.com/google/keep-sorted
    rev: v0.1.1
    hooks:
      - id: keep-sorted
